version: "3"

services:
  server:
    image: ghcr.io/kgtkr/anontown-server:20240112183237729-a6a9624
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?schema=public
      - SERVER_PORT=8080
      - REDIS_HOST=redis:6379
      - SALT_PASS=aaa
      - SALT_HASH=bbb
      - SALT_TOKEN=ccc
      - SALT_TOKEN_REQ=ddd
      - RECAPTCHA_SITE_KET=$RECAPTCHA_SITE_KET
      - RECAPTCHA_SECRET_KET=$RECAPTCHA_SECRET_KET
      - FAKTORY_URL=tcp://faktory:7419
      - VAPID_SUBJECT=mailto:anontown-dev@kgtkr.net
      - VAPID_PUBLIC_KEY=BCX9PMFDMoDEt_b-zDfPIgxM1aoishtKgBxkbGUQf-5uwWcLLJhwp0zHaHJaKVk-5lxHPmMvSPwtuC-9svBOGX0
      - VAPID_PRIVATE_KEY=nLViPPaqiG0LFPeEJkon8KbqBxgXTRSuujedJdFfycg
    depends_on:
      - postgres
      - redis
      - faktory
  redis:
    image: redis:5.0.14
    volumes:
      - redis:/var/lib/postgresql/data
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  camo:
    image: arachnysdocker/go-camo:2.3.1
    ports:
      - "4000:8080"
    environment:
      - GOCAMO_HMAC=${CAMO_KEY}
  faktory:
    image: contribsys/faktory:1.6.2
    volumes:
      - faktory:/var/lib/faktory/db
volumes:
  postgres:
  redis:
  faktory:
